app_admin/urls.py
from app_admin import views
from django.urls import path


app_name = 'admin'

urlpatterns = [
    path('home/',views.home,name='home'),
    path('logout/',views.logout,name='logout'),
    path('approve/<int:pid>',views.approve,name='approve'),
    path('reject/<int:pid>',views.reject,name='reject'),
]

common/urls.py
from . import views
from django.urls import path


app_name = 'common'

urlpatterns = [
    path('',views.home,name='home'),
    path('login',views.login,name='login'),
    path('signup',views.signup,name='signup'),
    path('username_exist',views.username_exist,name='username_exist'),
    path('admin/',views.admin_login,name='admin_login'),
]

crud_test/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('',include('common.urls')),
    path('user/',include('user.urls')),
    path('admin/',include('app_admin.urls')),
]

user/urls.py
from . import views
from django.urls import path


app_name = 'user'

urlpatterns = [
    path('',views.home,name='user_home'),
    path('create_post',views.create_post,name='create_post'),
    path('uploaded_post',views.uploaded_post,name='uploaded_post'),
    path('like_post/<int:pid>',views.like_post,name='like_post'),
    path('logout',views.logout,name='logout'),
]

app_admin/models.py
from django.db import models

# Create your models here.

common/models.py
from django.db import models

# Create your models here.

class User(models.Model):
    name = models.CharField(max_length=50)
    username = models.CharField(max_length=50)
    password = models.CharField(max_length=20)

    class Meta():
        db_table = 'customer'

class Admin(models.Model):
    username = models.CharField(max_length=50)
    password = models.CharField(max_length=20)

    class Meta():
        db_table = 'admin'

user/models.py
from django.db import models

# Create your models here.

class Post(models.Model):
    user = models.ForeignKey('common.User',on_delete=models.CASCADE)
    post = models.CharField(max_length=20000)
    status = 'pending'
    votes = models.IntegerField()
    status = models.CharField(max_length=10)

    class Meta():
        db_table = 'post'

class LikedPosts(models.Model):
    user = models.ForeignKey('common.User',on_delete= models.CASCADE)
    post = models.ForeignKey('Post',on_delete= models.CASCADE)

    class Meta():
        db_table = 'liked_posts'

app_admin/views.py
from django.shortcuts import render , redirect

from user.models import Post

# Create your views here.
def home(request):
    posts = Post.objects.filter(status = 'pending')

    return render(request, 'admin_temp/home.html',{'post':posts})

def logout(request):
    del request.session['admin']
    request.session.flush()
    return redirect('common:home')

def approve(request,pid):
    post = Post.objects.get(id = pid)
    post.status = 'approve'

    post.save()
    return redirect('admin:home')

def reject(request,pid):
    post = Post.objects.get(id = pid)
    post.delete()

    return redirect('admin:home')

common/views.py
from django.http import JsonResponse
from django.shortcuts import redirect, render

from common.models import Admin, User

# Create your views here.
def home(request):
    return render(request,"common_temp/home.html")

def login(request):
    msg = ''
    if request.method== 'POST':
        username = request.POST['username']
        password = request.POST['password']

        try:
            user = User.objects.get(username = username, password = password)
            request.session['user'] = user.id
            return redirect('user:user_home')
        except:
            msg = "Invalid User Id or Password"
    return render(request, "common_temp/login.html",{'msg':msg})

def signup(request):
    if request.method == 'POST':
            username = request.POST['username']
            password =  request.POST['repassword']
            name = request.POST['name']


            new_user = User(
                username = username,
                password = password,
                name = name
            )
            new_user.save()
            return redirect('common:login')
    
    return render(request, 'common_temp/signup.html')

def username_exist(request):
    username = request.POST['username']
    status = User.objects.filter(username=username).exists()
    return JsonResponse({'status': status})

def admin_login(request):
    msg = ''
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']

        try:
            admin = Admin.objects.get(username = username, password = password)
            request.session['admin'] = admin.id

            return redirect('admin:home')
        except:
            msg = 'Invalid ID or Password'
    return render(request, 'common_temp/admin_login.html',{'msg': msg})

user/views.py
from django.shortcuts import render,redirect
from common.models import User

from user.models import Post , LikedPosts

# Create your views here.

def home(request):
    post = Post.objects.filter(status = 'approve')
    return render(request, 'user_temp/home.html',{'post':post})


def create_post(request):
    msg = ''
    if request.method == 'POST':
        post = request.POST['post']
        userid = request.session['user']


        new_post = Post(
            user = User.objects.get(id = userid),
            post = post,
            votes = 0,
            status = 'pending'
        )
        msg = 'Uploaded Succesfully'

        new_post.save()
    return render(request, 'user_temp/create_post.html',{'msg':msg})


def uploaded_post(request):
    return render(request, 'user_temp/uploaded_post.html')


def like_post(request,pid):
    post_id = pid
    user_id = request.session['user']
    
    liked_user = LikedPosts.objects.filter(user_id=user_id, post_id = post_id).exists()
    post = Post.objects.get(id = pid)
    if liked_user == False:
        new_liked_post = LikedPosts(
            post_id = post_id,
            user_id = user_id

        )
        print(pid)
        
        new_liked_post.save()

        post.votes = post.votes + 1
        post.save()

    else:
        post.votes = post.votes - 1
        post.save()
        liked_post = LikedPosts.objects.get(user_id = request.session['user'], post_id = pid)
        liked_post.delete()
        print('true')
    
    return redirect('user:user_home')

def logout(request):
    del request.session['user']
    request.session.flush()
    
    return redirect('common:home')

app_admin/templates/admin_temp/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<style>
    .sticky {
        position: sticky;
        top: 0;
    }

    .nav_bar {
        display: flex;
        grid-template-columns: auto auto;
        justify-content: left;
        width: 100%;
        background-color: #b3f0ff;
        padding: 5px;

    }

    .nav_left {
        display: grid;
        grid-template-columns: auto auto;
    }

    .nav_left img {
        width: 100px;
        height: auto;
        z-index: 0;
    }

    .nav_right {
        display: flex;
        justify-content: center;
        padding-left: 500px;
        padding-top: 25px;
 
    }

    .nav_right a {
        padding: 10px;
        font-family: 'Poppins', sans-serif;
        background-color: #b3f0ff;
        text-decoration: none;
        color: black;
        font-weight: bold;
        justify-content: center;
    }
    .table{
        display: flex;
        justify-content: center;
        text-align: center;
        padding: 10px;
    }
    th,td{
        border: 2px solid black;
        padding: 10px;

    }
</style>

<body>
    <div class="sticky">
        <div class="nav_bar">
            <div class="nav_left">
                <img src="{% static 'common_static\images\reshot-icon-social-media-cloud-PS93DZTGYL.svg' %}" alt="">
                <h1>Shareit.</h1>
            </div>
            <div class="nav_right">
                <a href="{% url 'admin:logout' %}">Log Out</a>
            </div>
        </div>
    </div>
    <div class="content">
        {% for post in post %}
        <div class="table">
            <table>
                <th colspan="3"><h1 style="text-align: center;">Unapproved posts</h1></th>
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{post.post}}</td>
                    <td>
                        <button><a href="{% url 'admin:approve' post.id %}">Approve</a></button>
                        <button><a href="{% url 'admin:reject' post.id %}">Reject</a></button>
                    </td>
                </tr>
            </table>
        </div>
        {% endfor %}
    </div>
</body>

</html>

common/templates/common_temp/admin_login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<style>
    @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@600&display=swap');


    .login_card_outer {
        display: flex;
        justify-content: center;
        color: #330066;

    }

    .login_card {
        width: 30%;
        margin-top: 150px;
        margin-bottom: 150px;
        display: grid;
        grid-gap: 20px;
        justify-content: center;
        padding-bottom: 20px;
        box-shadow: 5px 5px 30px rgba(136, 136, 136, 0.513);
        background-color: #b3f0ff;
        font-family: 'Poppins';
    }

    .login_header {
        text-align: center;
        font-family: 'Poppins';
    }

    .login_form button {
        margin: 20px;
    }

    .login_form input {
        margin: 20px;
        display: flex;
        justify-content: center;
        text-decoration: none;
        border: 0px;
        color: black;
        /* box-shadow: 5px 5px 30px rgba(136, 136, 136, 0.513); */
        height: 25px;
        width: 300px;
        caret-color: rgb(232, 219, 219);
        font-family: 'Poppins';
        caret-color: #330066;
        background-color: rgba(234, 234, 234, 0.1);

    }

    .login_card button {
        text-decoration: none;
        border: 0px;
        color: rgb(0, 0, 0);
        /* box-shadow: 5px 5px 30px rgba(136, 136, 136, 0.513); */
        height: 25px;
        display: grid;
        justify-content: center;
        width: 300px;
        font-family: 'Poppins';
        background-color: white;
        transition: 0.3s;
        color: #330066;
    }

    .login_card button:hover {
        text-decoration: none;
        border: 0px;
        color: rgb(0, 0, 0);
        /* box-shadow: 5px 5px 30px rgba(136, 136, 136, 0.513); */
        height: 25px;
        display: grid;
        justify-content: center;
        width: 300px;
        font-family: 'Poppins';
        background-color: #330066;
        color: white;
        font-weight: bolder;
        transition: 0.3s;
        font-size: medium;
    }

    .forgot {
        font-family: 'Poppins';
        /* margin-left: 500px; */
        text-align: center;
        padding: 15px;


    }

    .forgot a {
        text-decoration: none;
        transition: 0.3s;
        color: #330066;
    }

    .forgot a:hover {
        text-decoration: none;
        color: #330066;
        font-size: large;
        transition: 0.3s;
    }

    .error {
        display: flex;
        justify-content: center;
    }

    .email_exist {
        text-align: center;
    }
</style>

<body>
    <div class="login_card_outer">
        <div class="login_card">
            <h1 class="login_header">Log In</h1>
            <form action="" class="login_form" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <input name="username" type="text" placeholder="Enter your Username">
                <input name="password" type="password" placeholder="Password">
                <button type="submit">Log In</button>
            </form>
            <div class="error">
                <span class="email_exist" id="email_exist">{{msg}}</span>
            </div>

        </div>
    </div>
</body>

</html>

common/templates/common_temp/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
</head>
<style>
    @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@600&family=Rubik+80s+Fade&display=swap');

    body {
        width: fit-content;
        font-family: 'Poppins', sans-serif;
    }

    body img {
        width: 100%;
        height: 100vh;
        object-fit: contain;
        z-index: -1;
    }

    .xbody {
        position: absolute;
        top: 0%;
        left: 0%;
    }

    .sticky {
        position: sticky;
        top: 0;
    }

    .nav_bar {
        display: flex;
        grid-template-columns: auto auto;
        justify-content: center;
        width: 100%;
        background-color: #b3f0ff;
        padding: 5px;

    }

    .nav_left {
        display: grid;
        grid-template-columns: auto auto;
    }

    .nav_left img {
        width: 100px;
        height: auto;
        z-index: 0;
    }

    .nav_right {
        display: flex;
        justify-content: left;
        padding-left: 1000px;
        padding-right: 99px;
        background-color: 0;
    }

    .nav_right a {
        padding: 10px;
        font-family: 'Poppins', sans-serif;
        text-decoration: none;
        background-color: #b3f0ff;
        color: white;
        background-color: #330066;
    }

    .nav_right button {
        padding: 0;
        border: none;
        background-color: none;
        background-color: none;
        margin: 10px;
    }
    .slogan{
        display: grid;
        grid-template-columns: auto auto auto;
        padding-top: 100px;
        justify-content: center;
        position: absolute;
        top: 100%;
        left: 45%;
    }
    .read{
        margin: 10px;
        color: #330066;
    }
    .write{
        margin: 10px;
        color:aqua;
    }
    .share{
        margin: 10px;
        color: #ff4da6;
    }
</style>

<body>
    <img src="{% static 'reshot-illustration-social-media-content-TVNWMBA6G3.png' %}" alt="sdg">
    <div class="xbody">
        <div class="sticky">
            <div class="nav_bar">
                <div class="nav_left">
                    <img src="{% static 'common_static\images\reshot-icon-social-media-cloud-PS93DZTGYL.svg' %}" alt="">
                    <h1>Shareit.</h1>
                </div>
                <div class="nav_right">
                    <button><a href="{% url 'common:login' %}">Log In</a></button>
                    <button><a href="{% url 'common:signup' %}">Sign Up</a></button>
                </div>
            </div>
        </div>
        <div class="content">
            <div class="slogan">
                <h1 class="read">Read</h1> <h1 class="write">Write</h1> <h1 class="share">Share</h1> 
            </div>
        </div>

    </div>
</body>

</html>

common/templates/common_temp/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<style>
    @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@600&display=swap');


    .login_card_outer {
        display: flex;
        justify-content: center;
        color: #330066;

    }

    .login_card {
        width: 30%;
        margin-top: 150px;
        margin-bottom: 150px;
        display: grid;
        grid-gap: 20px;
        justify-content: center;
        padding-bottom: 20px;
        box-shadow: 5px 5px 30px rgba(136, 136, 136, 0.513);
        background-color: #b3f0ff;
        font-family: 'Poppins';
    }

    .login_header {
        text-align: center;
        font-family: 'Poppins';
    }

    .login_form button {
        margin: 20px;
    }

    .login_form input {
        margin: 20px;
        display: flex;
        justify-content: center;
        text-decoration: none;
        border: 0px;
        color: black;
        /* box-shadow: 5px 5px 30px rgba(136, 136, 136, 0.513); */
        height: 25px;
        width: 300px;
        caret-color: rgb(232, 219, 219);
        font-family: 'Poppins';
        caret-color: #330066;
        background-color: rgba(234, 234, 234, 0.1);

    }

    .login_card button {
        text-decoration: none;
        border: 0px;
        color: rgb(0, 0, 0);
        /* box-shadow: 5px 5px 30px rgba(136, 136, 136, 0.513); */
        height: 25px;
        display: grid;
        justify-content: center;
        width: 300px;
        font-family: 'Poppins';
        background-color: white;
        transition: 0.3s;
        color: #330066;
    }

    .login_card button:hover {
        text-decoration: none;
        border: 0px;
        color: rgb(0, 0, 0);
        /* box-shadow: 5px 5px 30px rgba(136, 136, 136, 0.513); */
        height: 25px;
        display: grid;
        justify-content: center;
        width: 300px;
        font-family: 'Poppins';
        background-color: #330066;
        color: white;
        font-weight: bolder;
        transition: 0.3s;
        font-size: medium;
    }

    .forgot {
        font-family: 'Poppins';
        /* margin-left: 500px; */
        text-align: center;
        padding: 15px;


    }

    .forgot a {
        text-decoration: none;
        transition: 0.3s;
        color: #330066;
    }

    .forgot a:hover {
        text-decoration: none;
        color: #330066;
        font-size: large;
        transition: 0.3s;
    }

    .error {
        display: flex;
        justify-content: center;
    }

    .email_exist {
        text-align: center;
    }
</style>

<body>
    <div class="login_card_outer">
        <div class="login_card">
            <h1 class="login_header">Log In</h1>
            <form action="" class="login_form" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <input name="username" type="text" placeholder="Enter your Username">
                <input name="password" type="password" placeholder="Password">
                <button type="submit">Log In</button>
            </form>
            <div class="error">
                <span class="email_exist" id="email_exist">{{msg}}</span>
            </div>

        </div>
    </div>

    <div class="forgot">
        <a href="">Forgot Password?</a><br>
        <a href="">Don't have an account yet? Come Join</a>
    </div>
</body>

</html>

common/templates/common_temp/signup.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <script src="https://code.jquery.com/jquery-3.6.3.js"
        integrity="sha256-nQLuAZGRRcILA+6dMBOvcRh5Pe310sBpanc6+QBmyVM=" crossorigin="anonymous"></script>
</head>
<style>
    @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@600&display=swap');


    .login_card_outer {
        display: flex;
        justify-content: center;
        color: #330066;

    }

    .login_card {
        width: 30%;
        margin-top: 150px;
        margin-bottom: 150px;
        display: grid;
        grid-gap: 20px;
        justify-content: center;
        padding-bottom: 20px;
        box-shadow: 5px 5px 30px rgba(136, 136, 136, 0.513);
        background-color: #b3f0ff;
        font-family: 'Poppins';
    }

    .login_header {
        text-align: center;
        font-family: 'Poppins';
    }

    .login_form button {
        margin: 20px;
    }

    .login_form input {
        margin: 20px;
        display: flex;
        justify-content: center;
        text-decoration: none;
        border: 0px;
        color: black;
        /* box-shadow: 5px 5px 30px rgba(136, 136, 136, 0.513); */
        height: 25px;
        width: 300px;
        caret-color: rgb(232, 219, 219);
        font-family: 'Poppins';
        caret-color: #330066;
        background-color: rgba(234, 234, 234, 0.1);

    }

    .login_card button {
        text-decoration: none;
        border: 0px;
        color: rgb(0, 0, 0);
        /* box-shadow: 5px 5px 30px rgba(136, 136, 136, 0.513); */
        height: 25px;
        display: grid;
        justify-content: center;
        width: 300px;
        font-family: 'Poppins';
        background-color: white;
        transition: 0.3s;
        color: #330066;
    }

    .login_card button:hover {
        text-decoration: none;
        border: 0px;
        color: rgb(0, 0, 0);
        /* box-shadow: 5px 5px 30px rgba(136, 136, 136, 0.513); */
        height: 25px;
        display: grid;
        justify-content: center;
        width: 300px;
        font-family: 'Poppins';
        background-color: #330066;
        color: white;
        font-weight: bolder;
        transition: 0.3s;
        font-size: medium;
    }

    .forgot {
        font-family: 'Poppins';
        /* margin-left: 500px; */
        text-align: center;
        padding: 15px;


    }

    .forgot a {
        text-decoration: none;
        transition: 0.3s;
        color: #330066;
    }

    .forgot a:hover {
        text-decoration: none;
        color: #330066;
        font-size: large;
        transition: 0.3s;
    }

    .error {
        display: flex;
        justify-content: center;
    }

    .email_exist {
        text-align: center;
    }
</style>

<body>
    <div class="login_card_outer">
        <div class="login_card">
            <h1 class="login_header">Sign Up</h1>
            <form id="form" action="" class="login_form" method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                <input id="username" name="username" type="text" placeholder="User Name">
                <span id="ln_error"></span>
                <input id="password" name="password" type="password" placeholder="Password">
                <span id="email_error"></span>
                <input id="repassword" name="repassword" type="password" placeholder="Confirm Password">
                <span id="pass_error"></span>
                <input id="name" name="name" type="text" placeholder="Name">
                <span id="fn_error"></span>
                <button id="submit">Sign Up</button>
            </form>
            <div class="error">
                <span class="email_exist" id="email_exist"></span>
            </div>

        </div>
    </div>
    <script>
        $(document).ready(function () {
            console.log('ready')
            $('#repassword').change(function () {
                repass = $('#repassword').val()
                password = $('#password').val()
                error = $('#email_exist')


                if (password != repass) {
                    error.html("Passwords doesn't match")
                    $("#form").removeAttr('method');
                }
                else if (password == repass) {
                    error.html("");
                    $("#form").attr('method','POST')





                }
            })
        })

        $('#username').change(function () {

            $.ajaxSetup({
                headers: {
                    "X-CSRFToken": $('[name=csrfmiddlewaretoken]').val()  //passing csrf token in ajax request
                }
            })

            $.ajax({
                url: "{% url 'common:username_exist' %}",  // url in which ajax call is made
                type: 'POST',  //method in which data is send
                data: {
                    username: $(this).val()  //sending data in json fromat here, key is email
                },
                success: function (response) {
                    console.log(response.status)
                    if (response.status == true) {
                        $("#form").removeAttr('method')
                        

                        $('#email_exist').html('Username Already Taken');
                        $("#username").click(function () {
                            var email = $('#username').val("")
                            console.log(email.val)
                        })
                    }else{
                        $("#form").attr('method','POST')
                    }
                }
            })

        })
    </script>


</body>

</html>

user/templates/user_temp/create_post.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://code.jquery.com/jquery-3.6.3.js"
        integrity="sha256-nQLuAZGRRcILA+6dMBOvcRh5Pe310sBpanc6+QBmyVM=" crossorigin="anonymous"></script>
    <title>Document</title>
</head>
<style>
    .sticky {
        position: sticky;
        top: 0;
    }

    .nav_bar {
        display: flex;
        grid-template-columns: auto auto;
        justify-content: left;
        width: 100%;
        background-color: #b3f0ff;
        padding: 5px;

    }

    .nav_left {
        display: grid;
        grid-template-columns: auto auto;
    }

    .nav_left img {
        width: 100px;
        height: auto;
        z-index: 0;
    }

    .nav_right {
        display: flex;
        justify-content: center;
        padding-left: 500px;
        padding-top: 25px;

    }

    .nav_right a {
        padding: 10px;
        font-family: 'Poppins', sans-serif;
        background-color: #b3f0ff;
        text-decoration: none;
        color: black;
        font-weight: bold;
        justify-content: center;
    }

    .content {
        display: flex;
        justify-content: center;
    }

    form {
        padding: 50px;
        justify-content: center;
    }

    .content button {
        justify-content: center;
    }
</style>

<body>
    <div class="sticky">
        <div class="nav_bar">
            <div class="nav_left">
                <img src="{% static 'common_static\images\reshot-icon-social-media-cloud-PS93DZTGYL.svg' %}" alt="">
                <h1>Shareit.</h1>
            </div>
            <div class="nav_right">
                <a href="{% url 'user:uploaded_post' %}">Uploaded Posts</a>
                <a href="{% url 'user:logout' %}">Log Out</a>
            </div>
        </div>
    </div>
    <div class="content">
        <form id="form" action="" enctype="multipart/form-data">
            {% csrf_token %}
            <textarea name="post" id="post" cols="30" rows="10" placeholder="Enter your quotes here"></textarea><br>
            <input type="checkbox" name="" id=""> Agreed to the terms and conditions <br>
            <button id="button">Post</button>
            {{msg}}
        </form>
    </div>
    <script>
        $(document).ready(function () {
            console.log('ready')
            post = $('#post')



            $('#post').change(function () {
                console.log('hovered')
                if (post.val() != '') {
                    $('#form').attr('method', 'POST')
                }
            })

        })
    </script>
</body>

</html>

user/templates/user_temp/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>Document</title>
</head>
<style>
    .sticky {
        position: sticky;
        top: 0;
    }

    .nav_bar {
        display: flex;
        grid-template-columns: auto auto;
        justify-content: left;
        width: 100%;
        background-color: #b3f0ff;
        padding: 5px;

    }

    .nav_left {
        display: grid;
        grid-template-columns: auto auto;
    }

    .nav_left img {
        width: 100px;
        height: auto;
        z-index: 0;
    }

    .nav_right {
        display: flex;
        justify-content: center;
        padding-left: 500px;
        padding-top: 25px;
 
    }

    .nav_right a {
        padding: 10px;
        font-family: 'Poppins', sans-serif;
        background-color: #b3f0ff;
        text-decoration: none;
        color: black;
        font-weight: bold;
        justify-content: center;
    }
    .contents{
        padding-left: 200px;
        padding: 10px;
        margin: 50px;
    }
    .contents h1{
        text-align: center;
    }
</style>

<body>
    <div class="sticky">
        <div class="nav_bar">
            <div class="nav_left">
                <img src="{% static 'common_static\images\reshot-icon-social-media-cloud-PS93DZTGYL.svg' %}" alt="">
                <h1>Shareit.</h1>
            </div>
            <div class="nav_right">
                <a href="{% url 'user:create_post' %}">Create a Post</a>
                <a href="{% url 'user:logout' %}">Log Out</a>
            </div>
        </div>
    </div>
    <div class="contents">
        {% for post in post reversed %}
        {{post.user.username}}
        <h1> {{post.post}}</h1>
        <a href="{% url 'user:like_post' post.id %}"><i class="fa fa-thumbs-o-up" style="font-size:24px"></i></a>
        <strong>Liked by {{post.votes}} person</strong>
        <hr>
        {% endfor %}
    </div>
</body>

</html>

user/templates/user_temp/uploaded_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    uploaded posts
</body>
</html>